#version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0:8000'
    image: gss_api
    volumes:
      - .:/app
      - ${DATA_DIR}:/app/gss_data/
    ports:
      - 8000:80
    environment:
      - DATABASE_URLS=${DATABASE_URLS}
      - DATA_DIR=${DATA_DIR}
      - DEFAULT_DB_NAME=${DEFAULT_DB_NAME}
      - MAX_WORKERS=${MAX_WORKERS}  
    env_file:
      - .env

    #command: sh -c "printenv && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - ${DB_DATA_DIR}:/var/lib/postgresql/data/
    expose:
      - "${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
 
